### ISSUE TITLE
csv_path parameter missing from s3_to_rds() 

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#101]
I think we should decide on either `csv_path` (I'd personally prefer `file_name`, though) or `table_name`, unless there are cases when `table_name` would be different than the file name portion of `csv_path` (e.g when generating multiple tables from one csv). 

If this is the case, I suggest that the `table_name` parameter should be optional, and default should be the name of the csv.

**Comment by michalz92** [comment]
There's also some `s3_name` variable in the middle that I think is used instead of the `table_name` parameter?

**Comment by malinaa96** [comment]
Depends in which function. In `s3_to_rds` function we still use `s3_name` it can be different than the name of the table. I deleted it from `QFrame.to_rds` method and there by default the s3 file name is the same as the name of csv file.

We can agree on one version but I don't know which will be the best.

**Comment by michalz92** [comment]
Added new version to 0.2. for now. I will raise another issue to standardize parameters across the functions.
