### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by kfk** [kfk/grizly#102]
We need to add a requirements.txt file with all dependencies like

* sqlparse
* boto3

Etc.

There are many dependencies in this library so see if you can generate the main dependencies (the ones we import in grizly, not the system ones) with pip or other pythons system.

**Comment by malinaa96** [comment]
![image](https://user-images.githubusercontent.com/52569986/65406784-dce63d00-dde0-11e9-9e93-2bce1b8e17f9.png)

@acivitillo we already have this file no?

But probably we should have it here

![image](https://user-images.githubusercontent.com/52569986/65407183-02c01180-dde2-11e9-8ec6-c4c053ab28f8.png)

**Comment by acivitillo** [comment]
Yes we need to move it in the same folder where setup.py is. Then we need to change setup.py to do

`pip install -f requirements.txt`

This way the command

`python setup.py install`

Will also pull the dependencies of the library

Note, I am not sure if the flag is `-f`

**Comment by malinaa96** [comment]
Seems that we can't just put a command inside `setup.py`  but according to ([this](https://packaging.python.org/discussions/install-requires-vs-requirements/)) we can put some basic requirements in `setuptools.setup(install_requires=[list_of_our_requirements])` 
![image](https://user-images.githubusercontent.com/52569986/65521952-4f8f0f80-deea-11e9-9e3d-b3d25d5f3b47.png)

and additionally we can have the file with requirements which we can install using `pip install -r requirements.txt` command but if I understand it well we don't really need it, what do you think?

**Comment by malinaa96** [comment]
I fixed the requirements and I tested it on my computer and Mateusz computer. It seems that the only thing that everybody should have for this to work is to set the HTTPS_PROXY in environment variables. However I don't want to put it in grizly docs cause this one shouldn't be public.

@acivitillo if you don't mind I will just send an email to everybody or put it somewhere in team discussion and after this I will add the reqs to master branch

**Comment by acivitillo** [comment]
Kasia what you put in grizly docs is the process, you can put fake proxies

**Comment by malinaa96** [comment]
I added requirements file and it looks like this

![image](https://user-images.githubusercontent.com/52569986/67663250-626f8680-f965-11e9-8a01-f80b9b1d9917.png)

@acivitillo @michalz92 @pattrycja96 I'm reading this file line by line as a string so please make sure that whenever you are appending this file you don't put any comments or blank lines
