### ISSUE TITLE
Create tools.py file 

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#111]
Create file  *tools.py* in *core*. Add classes:
- [ ] **AWS** (file_name, s3_key, bucket, file_dir)

   Attributes:
    - [x] file_name
    - [x] s3_key
    - [x] bucket
    - [x] file_dir

   Methods:
    - [x] info
    - [x] df_to_s3 (df)
    - [x] file_to_s3 ()
    - [x] s3_to_file ()
    - [x] s3_to_rds ()

- [ ] **Excel** (excel_path)

    Attributes:
    - [x] input_excel_path [=excel_path]
    - [x] filename
    - [x] output_excel_path 

    Methods:
    - [ ] to_img (img_path,sheet, range)
    - [x] write_df (df, sheet, row, column)
    - [x] write_value (value, sheet, row, column)
    - [x] get_value (sheet, row, column) -> value
    - [ ] save
   <s>

    - [x]  open
    - [ ] hide_sheet (sheet)
    - [ ] hide_column (column)

- [ ] **Email**

    Attributes:
    - [ ] subject
    - [ ] email_recipients
    - [ ] message
    - [ ] attachments

    Methods:
    - [ ] send_email ()</s>

**Comment by malinaa96** [comment]
@kfk I prepared this structure of the classes. We can say that each of these classes represents an object 
- **AWSTools** represents a s3 file
- **ExcelTools** represents an Excel file
- **EmailTools** represents an email

I'm not sure now if the naming of these classes is correct now. Wouldn't it be better for example to have something like **Email** class instead of **EmailTools**? 
Also if we think about **ExcelTools** as an Excel file then I think we should change **to_excel** method to something like **import_df**.

**Comment by acivitillo** [comment]
Then it should be IExcel, IAWS or OExcel, OAWS. Meaning Input and Output. You can have an Excel Input (read) and an Excel Output (write).

**Comment by malinaa96** [comment]
I added **Excel** class https://github.com/kfk/grizly/blob/0.2/grizly/core/tools.py

It takes two arguments:
- excel_path
- output_excel_path (optional, by default the same as excel_path but with suffix '_working')

```python
from grizly import (
    get_path,
    Excel
)

excel_path = get_path('acoe_projects', 'testing', 'test.xlsx')
e = Excel(excel_path)

print(e.input_excel_path)
print(e.filename)
print(e.output_excel_path)
``` 
```
C:\Users\TE386850\acoe_projects\testing\test.xlsx
test.xlsx
C:\Users\TE386850\acoe_projects\testing\test_working.xlsx
```
Added also two methods **read_df** and **extract_value**. 
**read_df** method saves DataFrame in Excel specified in **output_excel_path** and overwrites **input_excel_path** with **output_excel_path**
```python
from pandas import DataFrame

df = DataFrame(data = {'col1': [1, 2], 'col2': [3, 4]})
e.read_df(df, sheet='weekly')

print(e.input_excel_path)
print(e.filename)
print(e.output_excel_path)
```
```
C:\Users\TE386850\acoe_projects\testing\test_working.xlsx
test_working.xlsx
C:\Users\TE386850\acoe_projects\testing\test_working.xlsx
```

**Comment by acivitillo** [comment]
@malinaa96 could you work on the AWS class today and tomorrow and add at least 

* df_to_s3
* s3_to_rds

those methods today do not work from the other library and I am not sure it's worth our time to fix them as they will be replaced by these ones. I really need to be able to load a df into rds and today we can't do that with grizly.

**Comment by malinaa96** [comment]
Added **AWS** class https://github.com/kfk/grizly/blob/0.2/grizly/core/tools.py.
At this moment it takes four arguments:
- file_name
- s3_key
- bucket
- file_dir

The user specifies them at the beginning and change them later as these are attributes of **AWS** class but he doesn't have to. With this solution it's easier to use methods as they are using the parameters saved in attributes. I created a small method **info()** which prints short summary of the class
```python
from grizly import AWS

aws = AWS()
aws.info()
```
```
 file_name: 	'test.csv'
 s3_key: 	'bulk/'
 bucket: 	'teis-data'
 file_dir: 	'C:\Users\my_id\s3_loads'
```
In this case we can see what are the defaults for the parameters. We can change them
```python
aws.file_name = 'my_excel.xlsx'
aws.s3_key = 'bulk/excel_loads/'
aws.info()
```
```
 file_name: 	'my_excel.xlsx'
 s3_key: 	'bulk/excel_loads/'
 bucket: 	'teis-data'
 file_dir: 	'C:\Users\TE386850\s3_loads'
```

I added also methods:
- file_to_s3()
- s3_to_file()
- df_to_s3(df)

Saving DataFrame in s3:
```python
from pandas import DataFrame

df = DataFrame({'col1': [1, 2], 'col2': [3, 4]})
aws = AWS()
aws.df_to_s3(df)
```
```
DataFrame saved in 'C:\Users\my_id\s3_loads\test.csv'
'test.csv' uploaded to 'teis-data' bucket as 'bulk/test.csv'
```

**Comment by malinaa96** [comment]
I didn't add yet the method `s3_to_rds` because I don't know how we should store the info about the columns and their types if we want to create a new table. Probably the easiest way would be to use PyAthena library (more info here https://github.com/kfk/grizly/issues/126) or we should have an argument with list of column names and their types I don't know.

**Comment by malinaa96** [comment]
I added `s3_to_rds` method. I'm using [select object content](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html). I used function from [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.select_object_content)

I'm quering an s3 object to get names of the columns and first 20 rows to set the types of the columns when the table doesn't exist in Redshift. 
```python
from grizly import AWS
from pandas import DataFrame

df = DataFrame({'col1': ['item1', 'item2'], 'col2': [1.3, 0.0], 'col_3': [None, None]})
aws = AWS()
aws.df_to_s3(df)

aws.s3_to_rds('test_kasia', 'testing')
```
```
DataFrame saved in 'C:\Users\TE386850\s3_loads\test.csv'
'test.csv' uploaded to 'teis-data' bucket as 'bulk/test.csv'
Table testing.test_kasia has been created successfully.
Loading bulk/test.csv data into testing.test_kasia ...
Data has been copied to testing.test_kasia
```

This creates following table:
![image](https://user-images.githubusercontent.com/52569986/66145466-31709000-e60b-11e9-8e7d-1a937b968be7.png)

![image](https://user-images.githubusercontent.com/52569986/66145455-2ae21880-e60b-11e9-8ad2-f5bf89b16771.png)

So every column which doesn't have float values has VARCHAR(500) type in Redshift

**Comment by malinaa96** [comment]
@acivitillo you added Email class to `email.py` so I deleted it from TODOs here. I'm also wandering if we will be able to do Excel.to_img without `win32`. If not maybe we should delete it from TODOs.

**Comment by malinaa96** [comment]
I think we don't need Excel class in 0.2 version so I'm just closing this one for now.
