### ISSUE TITLE
Start using PyAthena library to query s3 objects

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#126]
I found a nice library [PyAthena](https://pypi.org/project/PyAthena/) which we can use to query s3 objects directly in Amazon s3. I think it can we very useful for example to check the size of csv that we store in s3 or to get names of the columns without loading all data to local file. 

The library is very easy to use (we just need to create an engine string at the begging and then use SQL queries) but i have a problem with privileges.

While trying to run any query I get following error
![image](https://user-images.githubusercontent.com/52569986/65765196-e3015400-e127-11e9-8ba9-45dee3ac4150.png)

I found the error [here](https://docs.aws.amazon.com/athena/latest/ug/workgroups-troubleshooting.html) 
![image](https://user-images.githubusercontent.com/52569986/65765237-00362280-e128-11e9-8a2a-1049a7e02843.png)

@acivitillo if you think that you should use this library can you add us accesses to the workgroup? I'm not sure how to do this maybe this would help
https://docs.aws.amazon.com/athena/latest/ug/example-policies-workgroup.html

**Comment by acivitillo** [comment]
I am pretty sure Athena is another AWS service that we are currently not paying for. Why would you want to run SQL on top of S3?

**Comment by malinaa96** [comment]
As I wrote, when we query an s3 we can get the names of the columns. I don't know how to do s3_to_rds when the table doesn't exist in redshift - normally when I had QFrame I was getting the info about the columns from there but what if I just have a file in s3 and I want to save it in redshift?

**Comment by malinaa96** [comment]
Ok I found a new way:
https://medium.com/@bobhaffner/aws-s3-select-retrieving-subsets-of-tabular-files-7df36cd2d230
so we can use boto3 to query s3 objects I checked it and it's working so I will use this option.
