### ISSUE TITLE
Error fetching next row when fetching from Denodo

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#127]
It looks like this sometimes happens with large data.

> The suggestion above of using fetchone or fetchmany doesn't resolve the problem since, if you leave the name parameter unset, psycopg will by default attempt to load the entire query into ram.

The answer mentions `psycopg`, but I think it probably also affects `pyodbc`.

Solution :
Change `cursor = conn.cursor()` to `cursor = conn.cursor("my_cursor_name")` in `grizly.io.etl.to_csv()`

@acivitillo @malinaa96

**Comment by michalz92** [comment]
Copy of tedcs/infrastructure#20

**Comment by michalz92** [comment]
1. What actually happens under the hood is that the whole query is still read into memory, and only then the chunks are converted to python objects.
2. The way to overcome this is to use a so called "server-side cursor", but PyODBC does not have any for MSSQL.
3. Another way to circumvent this is to create a server-side cursor ourselves - it would be something like this:
```python
limit = chunksize
offset = 0
for chunk in chunksize:
    sql = f"""SELECT * FROM table_name LIMIT {limit} OFFSET {offset};"""
    cursor.execute(sql)
    rows = cursor.fetchall()
    if not rows:
        break
    writer.writerows(rows)
    offset += chunksize
    limit += chunksize
```

**Comment by michalz92** [comment]
@acivitillo @malinaa96

**Comment by malinaa96** [comment]
Are you sure that the third option will work? We were thinking about it because this part can be even done by the user - he can just change the limit in the loop but are you sure that we won't loose any rows or duplicate them?

**Comment by michalz92** [comment]
You have to use OFFSET and LIMIT in a loop to select consecutive chunks.

**Comment by kfk** [comment]
This change cursor = conn.cursor() to cursor = conn.cursor("my_cursor_name") in

Doesn't seem to work.

![image](https://user-images.githubusercontent.com/937922/65896324-4cde5f80-e3ad-11e9-9b61-9bd09c5f62a8.png)

**Comment by michalz92** [comment]
Hi, yes, sorry, looks like I forgot to revert it on github? This turned out to not be supported by pyodbc. It's supported by psycopg2 only.

**Comment by michalz92** [comment]
Also, did @malinaa96 share with you the code we wrote for this? We used grizly's built-in functionality to implement this "server-side chunksize" instead of the current pandas' cursor.fetchmany() client-side cursor.

**Comment by michalz92** [comment]
A workaround using `chunk_column` was added by Alessio to `grizly.Extract().from_sql()`.
