### ISSUE TITLE
Add column type support for utils.get_columns()

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#148]
Add the possibility to automatically load not only column names, but also data types, from both Redshift and Denodo.

- [x] Denodo

- [x] Redshift

**Comment by michalz92** [comment]
@acivitillo @malinaa96 
This will require agreeing on mappings from Denodo and Redshift types to ours.

**Comment by michalz92** [comment]
I've done it for Redshift; the function takes the datatypes straight from the source Redshift table.

**Comment by michalz92** [comment]
Usage:

```python
cols, types = grtizly.get_columns(schema=schema, table=table, db="redshift", column_types=True)
grizly.initiate(columns=cols, schema=schema, table=table, json_path=json_path, subquery=subquery, column_types=types)
```

**Comment by michalz92** [comment]
@pattrycja96 Does this work for Denodo?

**Comment by pattrycja96** [comment]
Yes, I am using this for Denodo ; )

```python
columns, columns_types = get_columns(schema_denodo, table_denodo, column_types = True)
initiate(columns, schema_denodo, table_denodo, json_path, subquery = table_denodo, col_types=columns_types
```
