### ISSUE TITLE
Added store and moved to master

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#162]
@malinaa96, @michalz92 please inform everybody that we moved to the master branch now.

Also note that there is a store concept now, please check the notebook store in notebooks folder and come back to me with questions. The reason for this was the excessive time it takes to type the fields for QFrame.select or QFrame.rename, highlighted by Valeria.

**Comment by michalz92** [comment]
Currently people use this:

```python
my_columns = [col1, col2]
columns, types = get_columns(schema='te_global_data', table='sales_weekly_flash', column_types=True, columns=my_columns)
initiate(columns=columns, col_types=types, schema='te_global_data', table='sales_weekly_flash', json_path=json_path, subquery='sales_weekly_flash')
```

And then they add the rest of the stuff to the JSON manually.

Maybe this should be a Store method instead?

BTW I think there's a mistake in the documentation:

> store.add_query(["col1", "col2"], "schema", "table", "query_2")
> store.to_store()
> The above will add a query named query_1 into the store. 

This will add query_2, not query_1, right?

**Comment by malinaa96** [comment]
It is a store method already `add_query` does the same as `initiate`

**Comment by acivitillo** [comment]
@michalz92 yes on what @malinaa96 said. Basically for now the code would be:

```python
q = QFrame().something
store = Store().add_query(q)
```

This is not taking in consideration any existing json like the ones we'll load into S3. Ideally we don't start from QFrame() but from an existing store query in S3.

Yes docs need fixing, can you do it?

**Comment by michalz92** [comment]
Ok, so you can pass columns and datatypes from `get_columns()` to `add_query()` to get the same output as with `initiate(get_columns())`, a QFrame prepopulated with fields and types from the original database? I thought you can only pass a query to `add_query()`.

**Comment by acivitillo** [comment]
I was wrong, it does not take a qframe, it takes the same input as initiate. Maybe we should change the name of this one to init_qframe() or something more clear.

```python
    def add_query(self, columns, schema, table, key_query, col_types=None):
        """Creates a dictionary with fields information for a Qframe and saves the data in json file.
        Parameters
        ----------
        columns : list
            List of columns.
        schema : str
            Name of schema.
        table : str
            Name of table.
        key_query : str, optional
            Name of the query in json file. If this name already exists it will be overwritten, by default ''
        col_type : list
            List of data types of columns (in 'columns' list)
        """
```
