### ISSUE TITLE
Add doc string to email class

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#165]
Please add doc strings to the newly created class in master: 

https://github.com/kfk/grizly/blob/master/grizly/email.py

**Comment by acivitillo** [comment]
Is this done?

**Comment by malinaa96** [comment]
Not yet

**Comment by malinaa96** [comment]
Added with https://github.com/kfk/grizly/pull/279

https://grizly-docs.readthedocs.io/en/0.3/content/api_Email.html

I'm missing only description to these two parameters
![image](https://user-images.githubusercontent.com/52569986/71616158-18995b80-2bb5-11ea-9d26-75fb60814594.png)

We can add it later
