### ISSUE TITLE
0.3 version

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#166]
Are you all ok to clone 0.2 into a new branch 0.3? I think we are mostly done with 0.2. Also here is what I would like to do moving forward:

* For breaking changes (things that break existing grizly code) we follow a release model (0.2, 0.3, etc.) and we only move to master AFTER communicating the changes to the team
* For non breaking changes we can still do silent releases into Master w/o informing the team

Please write your thoughts here and let's come to a decision by end of this week

**Comment by michalz92** [comment]
I agree.

**Comment by malinaa96** [comment]
I think we can add a new branch 0.3 where we add new classes but 0.2 is not really finished yet. We miss tests and docstrings in many functions. I think we should clean this up before closing 0.2

**Comment by pattrycja96** [comment]
I don't work a lot with grizly but I agree with the idea. But Kasia is also right, we should firstly complete 0.2.

**Comment by acivitillo** [comment]
We will create a *closing 0.2* milestone and we will put all the issues there. Once the issues are closed we'll close 0.2.
