### ISSUE TITLE
get_path(from_where='here') depends on jupyter config file

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#170]
I found out that when we specify a directory in jupyter configuration file 

![image](https://user-images.githubusercontent.com/52569986/67398917-b5cf8680-f5ab-11e9-8547-399af8ba2a7d.png)

then `get_path(from_where='here')` works like this

![image](https://user-images.githubusercontent.com/52569986/67400972-ba496e80-f5ae-11e9-8130-9631e3abbc49.png)

And when we don't specify any path

![image](https://user-images.githubusercontent.com/52569986/67401236-288e3100-f5af-11e9-8f1b-df0fd5880375.png)

then get_path(from_where='here')` works like

![image](https://user-images.githubusercontent.com/52569986/67401330-4b204a00-f5af-11e9-9378-103c36fd2fd2.png)

@acivitillo what do you think about it? Should we all leave the default directory as it is in the second option or should we modify `get_path` function?

**Comment by acivitillo** [comment]
Get path starts from the directory of the python script which for jupyter notebooks is defined in the config file. I don't think it's a bug but definitely we should mention it in the docs and also the get_path docstring.

**Comment by malinaa96** [comment]
So you say that we should have the path specified in jupyter config file or not?

**Comment by malinaa96** [comment]
I also didn't realize that when you don't specify it in jupyter config file then your directory is always the one where your notebook is
![image](https://user-images.githubusercontent.com/52569986/67479155-bc1e3b00-f65d-11e9-87b7-b4151f7288b7.png)

**Comment by acivitillo** [comment]
My concern if we don't put it in the config file is that people will start creating their own structures and this will be messy, so I'd stick to the config file. We also need to align the path config with the VM paths @michalz92

**Comment by malinaa96** [comment]
As we want to specify the path in config file then the option `get_path(from_where='here')` doesn't work as it suppose to. Can we delete this option?

**Comment by michalz92** [comment]
Shouldn't get_path just start from the user directory, `C:/Users/TE123456`? This makes it independent of other configs and works as expected. We can add a clause for Linux for this to work on VM. You can do it like this:

```python
if os.name == "nt":
    get_windows_home_dir()
else:
    get_linux_home_dir()
```

**Comment by malinaa96** [comment]
We will go back to old functionality.
