### ISSUE TITLE
grizly running talking points and decisions

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#179]
# Decisions

### PR review process

*Decision* each PR has to point to a reviewer in comment section. Also, we'll make a good commentary going forward for each PR

*Reasoning* keep each other aligned

### documentation

* Create git issue on docs if docs are not sufficient or clear enough
* Spend some time creating docs on grizly but also coding practices

### Old crap

* For now keep but for 0.3 we need to agree on which functions we remove

# Proposals

### Dec 9 2019

* Branch 0.3_tools_folder. Added tools folder and started to move grizly tests and modules to relative imports. `import from grizly` is a bad idea since when testing it will import from the installed grizly and not the development version
* Can we close the Config section here below? I think we have an agreement on the path forward for Config()?

**Comment by malinaa96** [comment]
Issues to discuss https://github.com/kfk/grizly/issues/170 https://github.com/kfk/grizly/issues/169 (also argument naming in join)

**Comment by malinaa96** [comment]
Decisions
===

QFrame
---
- Add a tutorial to union
- Add short explanation to docstring in union
- Leave join. Add validations in join
- Try to create docs as in pandas but don;t spend much time on this one. Make sure that side bar is working

Config
---
We agreed on the second approach:
```
{
  "historical_backlog_is": {},
  "some_configs":{}
}
```
Closing 0.2 release
---
We will close 0.2 this week.

**Comment by michalz92** [comment]
To discuss naming in the AWS class.

**Comment by acivitillo** [comment]
s3.list()

**Comment by acivitillo** [comment]
Some stuff I did over the weekend, we can discuss tomorrow.

Please remember we still need to do some clean up, AWS is still called AWS (and should be S3) and tools.py needs to go.

Priority goes to config.py of course but it seems we are getting it under control.

- created init subquery ui, try it with QFrame().build_subquery()
- created simple field edit/build, you can try it with QFrame().build_field()
- added key "engine" inside qframe select. I find it easier if the engine is in the json too to avoid QFrame(engine=...)
- todo: get_subqueries in ui.py needs a proper look, right now it mixes subqueries with other keys

**Comment by acivitillo** [comment]
Another note, I am still not sure about Extract and Load. If we accept the idea that the Class is the *thing* then Classes should not be verbs. Meaning, a class should be a noun and a method should be a verb.

The immediate impact of that is that we don't have an `Extract().from_sfdc`. We have a SFDC() class on which we do stuff. So we should have SFDC().from_table("opportunity") or SFDC().from_soql().

It will mean more duplication of extractors and loaders but it's more clean and it is easier to code.

What do you think?

**Comment by acivitillo** [comment]
QFrame.select() should possibly also write the new subquery inside the store.json. Right now it doesn't and it's confusing especially if we try to build a UI on top.

**Comment by malinaa96** [comment]
Well you can write it to store by doing `QFrame.save_json()`. If you want to add option to `QFrame.select()`  to write the subquery to json then we should add it to every method that changes the final SQL, in other case it would be misleading.

**Comment by malinaa96** [comment]
# Proposals
- Find commonalities of the classes so that we can create one parent class

**Comment by acivitillo** [comment]
I think those things are in common:

* data inside a dataframe inside __init__()
* to_csv() of the __init__() df
* to_rds() of the __init__() df
