### ISSUE TITLE
QFrame() works by default with engine=denodo

### ISSUE THREAD

**Issue by vperluzzo** [kfk/grizly#190]
Hi! We have been working with grizly on the is_moq compilation workflow and we didnt remember to use the QFrame(engine="redshift...") so we were actually querying denodo.

It took us a while to actually realize that this was the issue because the error was not helpful

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1: invalid start byte 

Is there a way to improve the error, so it will tell you
"There is no schema "squema requested" in Denodo"

**Comment by vperluzzo** [comment]
@malinaa96

**Comment by malinaa96** [comment]
We get this error always when there is a problem in Denodo but we can't read what problem is that it's always utf-8 error. @michalz92 am I right?

**Comment by vperluzzo** [comment]
how about switching to default - redshift?

**Comment by michalz92** [comment]
That would break existing workflows, so I would keep it as it is until we have the loads working. You just need to remember to specify the database from which you want to pull data. A good practice is to always check the parameters of each function and class you're using.

**Comment by vperluzzo** [comment]
ok understood
