### ISSUE TITLE
Redshift_str need to be put in many places if using new Redshift

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#204]
E.g. if a wf uses check_if_exists, it has to be put in several places. Could we change the default to the new Redshift instead?

@malinaa96

**Comment by michalz92** [comment]
The problem is that it's hard to debug for the python newbies.

**Comment by malinaa96** [comment]
We can to this but we have to agree with the whole team because it will break their workflows if they are writing some data to the old redshift.

**Comment by michalz92** [comment]
I think we can just remove the keyword whenever we can get it from QF. And also I got it wrong, we only needed to specify it in one place.
