### ISSUE TITLE
s3 path - remove "bulk/"

### ISSUE THREAD

**Issue by krzyzanowskik** [kfk/grizly#207]
@acivitillo

Hi Kasia,
as I understand s3 path with "bulk/" is hard-coded in grizly.
Is it possible to remove "bulk/" in next release?

**Comment by acivitillo** [comment]
Guys let's close this one, it should be easy. @malinaa96 can you do it still today? Only in 0.3.

**Comment by malinaa96** [comment]
Ok, I will do it after adding the tutorials

**Comment by malinaa96** [comment]
Done in 0.3 branch
