### ISSUE TITLE
to_rds - REMOVEQUOTES

### ISSUE THREAD

**Issue by pattrycja96** [kfk/grizly#209]
Hi guys, can we add a parameter like remove_quotes='all'/'outer' (with 'outer' as default) to the function to_rds and s3_to_rds?
There are some columns in Denodo with " or ' in the middle of string and we have errors with loading the data.  For me ``` CSV QUOTE AS '\"' ``` instead of ```REMOVEQUOTES``` was enough.

**Comment by michalz92** [comment]
We can extend `etl.build_copy_statement()` to accommodate for this.

**Comment by michalz92** [comment]
For now, added with #226 as the `remove_iside_quotes` parameter to `etl.s3_to_rds()`. I'm not sure if this escapes all quotes or only those in the middle; it seems to me that `REMOVEQUOTES` only escapes the outer quotes, while `CSV QUOTE AS` only removes inside quotes (so not all of them). Would have to test to confirm. For now` CSV QUOTE AS` worked for my case.

**Comment by michalz92** [comment]
Let's close this for now and once we find out what these functions exactly do, we can add the remove_quotes parameter Pati mentioned above.
