### ISSUE TITLE
Change scheduler's queueing process

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#210]
It should utilize a `workflow_queue` table, which will contain one row for each workflow, with the next run date and other metadata.

**Comment by michalz92** [comment]
This is a major change. @acivitillo would need to brainstorm it

**Comment by acivitillo** [comment]
Yes we need to brainstorm this because I think we need to put the queue in a sql table. This would allow us to merge manual and automated scheduling into 1 state controlled in 1 place.

**Comment by michalz92** [comment]
This will be done with the `dask.distributed` scheduler.
