### ISSUE TITLE
Grizly formula copy from s3 to s3

### ISSUE THREAD

**Issue by krzyzanowskik** [kfk/grizly#213]
Hi Kasia,

as we were talking it would be great to have a formula which copy the entire folder data from s3 to another s3.
There is a need to make backups for Denodo tables, but we want to stash them only in s3.
I have found that:
_[from s3://acoe-s3/bulk/data_loads/sales_weekly_flash/ to s3://acoe-s3/bulk/backup/sales_weekly_flash/]_
```
import subprocess
subprocess.run(["aws", "s3", "sync", "s3://acoe-s3/bulk/data_loads/sales_weekly_flash/", "s3://acoe-s3/bulk/backup/sales_weekly_flash/"])
```
is working, however having a formula would be great.
Please let me know if you have any questions.
Thanks!

**Comment by malinaa96** [comment]
I think this can be a new feature in `AWS` class we can call it `s3_to_s3`. We wouldn't put it in `Load` or `Extract` class as we don't want to download the s3 to local file - we just want to copy one s3 to another s3. The usage would be:
```python
old_s3 = AWS(file_name, s3_key, bucket)
new_s3 = old_s3.s3_to_s3(new_file_name, new_s3_key, new_bucket)  # <- this will return AWS class with new parameters
```

We can call it in other way maybe `move` or something but with `s3_to_s3` we keep the same convention as we have in `AWS` class as we already have `file_to_s3`, `df_to_s3`, `s3_to_file` and so on.

@acivitillo @michalz92 what do you think?

**Comment by michalz92** [comment]
I think this should just be called `copy`.
E.g. 
```python
s3_file = AWS()
s3_file.copy(to=backup_path)
```

The method would look something like this:
```python
def copy_file(self):
    s3 = boto3.resource(‘s3’)
    s3.Object(bucket_name, path_b).copy_from(CopySource=path_a)
```

**Comment by malinaa96** [comment]
But look [here](https://grizly-docs.readthedocs.io/en/master/content/api_AWS.html) 
![image](https://user-images.githubusercontent.com/52569986/68673841-ea07e880-0554-11ea-83e7-ac4042c078b2.png)


We can keep the same convention with the naming by using `s3_to_s3`. The `copy` can be misleading if you look for a method to copy s3 to local file.

**Comment by acivitillo** [comment]
Hi looks good keep in mind we also need an s3_delete(key) function.

Sent from my iPhone

On 12. Nov 2019, at 12:15, malinaa96 <notifications@github.com<mailto:notifications@github.com>> wrote:


The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

I think this can be a new feature in AWS class we can call it s3_to_s3. We wouldn't put it in Load or Extract class as we don't want to download the s3 to local file - we just want to copy one s3 to another s3. The usage would be:

old_s3 = AWS(file_name, s3_key, bucket)
new_s3 = old_s3.s3_to_s3(new_file_name, new_s3_key, new_bucket)  # <- this will return AWS class with new parameters

We can call it in other way maybe move or something but with s3_to_s3 we keep the same convention as we have in AWS class as we already have file_to_s3, df_to_s3, s3_to_file and so on.

@acivitillo<https://github.com/acivitillo> @michalz92<https://github.com/michalz92> what do you think?

**Comment by malinaa96** [comment]
I added `s3_to_s3` ([docs](https://grizly-docs.readthedocs.io/en/master/content/api_AWS.html#grizly.AWS.s3_to_s3))

![image](https://user-images.githubusercontent.com/52569986/69035066-fd96d180-09e2-11ea-8df1-539703109c52.png)

With this function we can only move one file at a time. 

Should I add a method to copy every file from key specified in `AWS.s3_key` to another key or a method which returns list of files in specified key so that the user will be able to copy them one by one in the loop? @acivitillo @michalz92 what do you think?

**Comment by michalz92** [comment]
Well, you know what I think. I think this class is way too unintuitive for what it does. Anyway, as far as I understand the AWS class, it's actually an S3 bucket object. So you can iterate through the keys inside the bucket and copy them in a loop:

```python
for key in bucket.list():
    new_key = key.replace(old_dir, new_dir)
    s3.s3_to_s3(from=key, to=new_key)
```

**Comment by acivitillo** [comment]
@michalz92 a lot of grizly is a wrapper around other stuff so we have a pandas-like api around different libraries. For sure we could leverage boto3 as you do above but that means we give our team more than 1 way to do something and easily they can end up with a lot of non standard code.

@malinaa96 let's start using this first method first before we add new ones. I think we probably need at least an s3_list(key="some_key") method to do the above @michalz92  is doing.

**Comment by michalz92** [comment]
I think this should be included inside `s3_to_s3`. To keep things intuitive, the user shouldn't care if they're copying a file or a folder, so both cases should be handled inside the function.

**Comment by acivitillo** [comment]
That makes sense

**Comment by michalz92** [comment]
@malinaa96 This is added already, right?

**Comment by malinaa96** [comment]
Nope, I'm still working in the Config class

**Comment by malinaa96** [comment]
I added also `S3.list()` method with https://github.com/kfk/grizly/pull/239. Now if you want to for example copy all files from `bulk/test/` to`bulk/test_backup/test/`  you can do
```python
s3 = S3('', 'bulk/test/')
for file in s3.list():
    s3_old = S3(file_name=file, s3_key='bulk/test/') 
    s3_old.copy_to(s3_key='bulk/test_backup/test/')
```

**Comment by michalz92** [comment]
@malinaa96 One improvement I see here, is that .list() could return an iterator through S3 objects within the key. So you would have:

```python
cur_dir = S3("bullk/test")
new_dir = S3('bulk/test_backup/test/') # it's a bit confusing to me that we copy form an S3 object to a string. Shouldn't both directories be S3 objects like this?
for file in cur_dir:
    file.copy_to(new_dir)
```

**Comment by malinaa96** [comment]
You want `S3.list()` to return list of S3 classes?
