### ISSUE TITLE
to_rds if_exists = "replace" not working

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#214]
The below code throws a "sql table already exists" error, seems like the if_exists flag *replace* is not working.

```python
def upload_df(df, configs):
    load = Load(file_path = extract_path)
    load.to_rds(table = "git_acoe_issues", schema="data_loads",if_exists="replace"
                , redshift_str = configs["engine_str"], bucket="teis-data", sep="\t")
```

**Comment by malinaa96** [comment]
Yes I fund a bug
![image](https://user-images.githubusercontent.com/52569986/68654662-b74af980-052e-11ea-8cfc-98a803b97841.png)
 I forgot to put `redshift_str` in `check_if_exists` I will fix it.

**Comment by malinaa96** [comment]
I fixed it on 0.3 branch, let me know when you check if it fixes the problem.

**Comment by acivitillo** [comment]
Can you merge to master?

**Comment by malinaa96** [comment]
Done
