### ISSUE TITLE
api structure

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#225]
@malinaa96 and @michalz92 as I think about the next steps for Grizly I keep coming to the same structure each time. We are more are more *componetizing* this. 

It seems we always do this:

* Input
* Some actions on the object
* Output

Which looks like this:

* Input: QFrame().read_json()
* Actions: QFrame().join()
* Output: QFrame().to_df()

I think that means we could standardize most of the api like so:

* Input: Class().from_
* Output: Class().to_
* Actions: we can standardize this a bit but I am not sure yet about the best approach

**Comment by malinaa96** [comment]
For me it looks good. I see that you have two options 
- Class().from_
- Class().read_

Is there any difference between these two?
