### ISSUE TITLE
ec2 setup.py install does not install all libraries

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#231]
For instance it does not install boto3. I think for some reason the install is running the install for the wrong version of python.

**Comment by acivitillo** [comment]
This is because of the problem with xlwings

**Comment by michalz92** [comment]
Is this still an issue? I think we can use below snippet to work around this.

```python
setup(
    name="Project",
    ...
    install_requires=[
        'enum34 ; python_version<"3.4"',
        'pywin32 >= 1.0 ; platform_system=="Windows"'
    ]
)
```
