### ISSUE TITLE
read_config() is Windows only

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#232]
Because of this

```
os.environ['USERPROFILE']
```

read_config() in utils.py is Windows only. I guess this will go away and be replaced by our Config() class?

**Comment by malinaa96** [comment]
Yes and in fact this issue corresponds to this https://github.com/kfk/grizly/issues/91

**Comment by michalz92** [comment]
https://stackoverflow.com/questions/26722607/cross-platform-method-to-obtain-the-users-configuration-home-directory-in-pytho
