### ISSUE TITLE
S3 connection doesn't work

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#245]
S3 connection doesn't work for any grizly.etl functions because of the removed config lines.

The workaround is to readd the following lines to etl.py:

```python
from .utils import read_config
config = read_config()
try:
    os.environ["HTTPS_PROXY"] = config["https"]
except TypeError:
    pass
```

Apparently, the config from env variables is not applied to all connections - I think it depends on internal code of the external libraries we use. I also had to specify proxy inside SFDC class to make it work. I think we should consider setting the env proxies as default similar to the code we had originally, but now using Config class?

@malinaa96 @acivitillo

**Comment by michalz92** [comment]
To check in boto how we can specify proxy on connection, so we can use config to specify them.

**Comment by malinaa96** [comment]
There will be only one proxy for every function?

**Comment by acivitillo** [comment]
Yes I would say 1 proxy for 1 workflow

Sent from my iPhone

On 9. Dec 2019, at 08:35, malinaa96 <notifications@github.com<mailto:notifications@github.com>> wrote:


The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

There will be only one proxy for every function?

**Comment by acivitillo** [comment]
Actually 1 proxy for 1 user

Sent from my iPhone

On 9. Dec 2019, at 08:35, malinaa96 <notifications@github.com<mailto:notifications@github.com>> wrote:


The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

There will be only one proxy for every function?

**Comment by malinaa96** [comment]
Ok so I would put it like this

```python 
{
  "config": {
    "standard": {
      "email": {
        "email_address": "my_email@example.com",
        "email_password": "my_password",
        "send_as": "Team"
      },
      "github": {
        "username": "my_login",
        "username_password": "my_password"
      },
      "sfdc": {
        "stage": {
          "username": "my_login",
          "instance_url": "https://na1.salesforce.com",
          "password": "my_password",
          "organizationId": "OrgId"
        },
        "prod": {
          "username": "my_login",
          "password": "my_password",
          "organizationId": "OrgId"
        }
      },
      "proxy": "some_proxy"
    }
  }
}
```

**Comment by michalz92** [comment]
That's fine, just note we need both http and https proxies just in case.

**Comment by michalz92** [comment]
Fixed by rolling back to using env variable, which value is taken from config. S3 class should use the proxy from config, though, as a long term solution.
