### ISSUE TITLE
Logger config should be part of global config?

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#246]
TBD. I feel like a separate file for this is a bit clumsy. Also, think some users will want to specify their own logging and even different config per workflow.

**Comment by acivitillo** [comment]
Yes all configs should be in config and config should be in store.json

**Comment by michalz92** [comment]
Reopening since it's a to do. I can do this during the vacation time.

**Comment by michalz92** [comment]
I want to keep it explicit for now, since Config is not very stable and hard to debug.
