### ISSUE TITLE
get_path() function not compatible with network drive

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#247]
Input: address = get_path(r'\\NLXXX','A','B','','C','D')
Output: 'C:\\\\NLXXX\\A\\B\\C\\D'
Desired output: \\\\NLXXX\\A\\B\\C\\D

the header C:\ is automatically added. Need to connect network drive.

**Comment by acivitillo** [comment]
How do you connect to a file in a drive today? Do you use os?

**Comment by michalz92** [comment]
I think get_path returns a path to HOME dir by default, to which you append the rest of your path. The function name is misleading, as it should probably be `get_home_path()`.  This is essentially the same as using `os.path.expanduser(path)`, and then joining the paths with `os.path.join()`. In your case, you're not starting from home dir, so you can just type the path directly or using `os.path.join()`.
