### ISSUE TITLE
hardcoded value in orchestrate creates issue with Email

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#248]
![image](https://user-images.githubusercontent.com/54931660/70324483-de47d300-182f-11ea-969d-c2410e29159d.png)

**Comment by michalz92** [comment]
Yeah, I see you've changed default to None now so I'm closing this one. 

Also, we need to figure out a consistent way of passing arguments to Workflow. I've added `execution_options` argument to handle single_threaded runs, so you specify `execution_options={"scheduler": "single-threaded"}`. Not sure if this should be done this way (grouping parameters, e.g. `execution_options`, `notification_options`, etc.) or if we should just keep adding parameters, such as 
```python
wf = Workflow(name="test", ..., env="local", scheduler="single_threaded", send_as="team@mailbox.com", ...)
```

**Comment by michalz92** [comment]
Fixed.
