### ISSUE TITLE
Run docstring examples

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#250]
I don't know if you knew this but we can also run examples that are written inside doc strings using [doctest](https://docs.python.org/2/library/doctest.html). I think we should definitely do this as the doc strings go to grizly documentation and they should be 100% correct. Also with this we don't have to manually check each doc string every time when we change something in the class. 

So the only thing we need t do is to add 

```python 
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```
to each module and then run 
```python
python module.py
```
in the terminal. I checked for example the `config.py` file and I got
![image](https://user-images.githubusercontent.com/52569986/70421568-4bdf4380-1a6a-11ea-948b-5d0a511ae40d.png)

then to each test we see what are the errors 
![image](https://user-images.githubusercontent.com/52569986/70421635-74ffd400-1a6a-11ea-83ae-5bab7174b661.png)

I have only two issues with that.
First, we can't have `email.py` file as there is a built in library in python called `email` and I got errors because of that.
Second, we have to import the modules like `grizly.etl` not `.etl` because with the second option I'm also getting errors.

@acivitillo @michalz92 let me know what you think about it, for me we should definitely use doctest.

**Comment by acivitillo** [comment]
we should be able to run tests on the library w/o having to install the library. So we should be able to do imports like `.etl` because the `grizly.etl` import is going to go to the installed version of grizly.

**Comment by malinaa96** [comment]
Well for me it works without installing grizly every time the only thing I have to do is to save the file and then run the tests one more time. I think we should do it as we were doing it from the beginning this means `grizly.etl` because without `grizly` prefix all my tests fail. Also they do it like this in other libraries like pandas or boto3.

**Comment by acivitillo** [comment]
> the only thing I have to do is to save the file and then run the tests one more time

I am not sure what that means

**Comment by malinaa96** [comment]
With this 
![image](https://user-images.githubusercontent.com/52569986/70425561-bd6ec000-1a71-11ea-81ae-c1f6c375807b.png)

I got this error 
![image](https://user-images.githubusercontent.com/52569986/70425606-ce1f3600-1a71-11ea-8413-8684ddbed29f.png)

When I do 
![image](https://user-images.githubusercontent.com/52569986/70425650-e3946000-1a71-11ea-8750-530039bdbbdc.png)

I don't get any error. So for me it's better to use it like this. I don't have t install grizly every time I run the tests - it's enough if I save the file.

**Comment by acivitillo** [comment]
> it's enough if I save the file.

For me that is not working, also I would park the doc string conversation for now. It's a really good idea but I want us to focus on getting config 0.3 stable for now.

**Comment by malinaa96** [comment]
I found an option to run doc strings via `pytest`. You just have to do 
```
pytest --doctest-modules
```
to run all modules or
```
pytest --doctest-modules config.py
```
to run only `config` module for example and it runs examples in doc strings. I think it's te best solution and I will be using this to check if the doc strings are updated.

**Comment by acivitillo** [comment]
Can we create a test.py script to run all the tests we need to run both __doc__ strings and modules?

**Comment by malinaa96** [comment]
I have this extention in Visual Studio Code to run tests
![image](https://user-images.githubusercontent.com/52569986/70442712-2583cd00-1a97-11ea-841c-0870c7556636.png)
I will try to figure out how to add also doc string tests here.

**Comment by malinaa96** [comment]
We can also try to use this github actions to run the tests automatically.
