### ISSUE TITLE
get_columns()/get_redshift_columns hard coded 'mssql+pyodbc://Redshift'

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#259]
In master branch:

the get_columns() function is using get_redshift_columns that only look at DSN Redshift. Need to customize to redshift_acoe.

def get_redshift_columns(schema, table, column_types=False):
    """Get column names (and optionally types) from a Redshift table.

    Parameters
    ----------
    schema : str
        Name of schema.
    table : str
        Name of table.
    column_types : bool
        Whether to retrieve field types.
    date_format : str
        Denodo date format differs from those from other databases. User can choose which format is desired.
    """
    con = get_connection(db="redshift")
    cursor = con.cursor()
    sql = f"""
        SELECT ordinal_position AS position, column_name, data_type,
        CASE WHEN character_maximum_length IS NOT NULL
        THEN character_maximum_length
        ELSE numeric_precision END AS max_length
        FROM information_schema.columns
        WHERE table_name = '{table}' AND table_schema = '{schema}'
        ORDER BY ordinal_position;
        """
    cursor.execute(sql)

**Comment by acivitillo** [comment]
@bing9 we'll fix this in 0.3 only for now

**Comment by michalz92** [comment]
Get_columns is only using get_redshift_columns by default, you can specify the db with the `db` parameter. However this db is then looked up in your .grizly config file (e.g. "denodo" will look for the "denodo" key in your config".

**Comment by acivitillo** [comment]
Yeah we need to change the look up from the .grizly to the Config() class

Or not? I mean this is the dsn string right?

**Comment by michalz92** [comment]
Well the logic depends on db, so we'd have to change the function a bit. This doesn't rely on DSN because you could name your Denodo DSN as "TE_DB1", or whatever.

**Comment by michalz92** [comment]
At the same time I think we should keep this `get_columns()` function that serves as API to the lower level `get_dbname_columns()` functions, because we will provably have many of these in the future (we already have 3).

**Comment by acivitillo** [comment]
So if we add a service in Config like {“config”:”databases” : {“denodo_prod” : “dsn”:”some_engine_str”}}

Would that make sense? Then we can pick the details from the database name (like denodo_prod in this case).

**Comment by michalz92** [comment]
Yes, that would be good, as long as the keys can be resolved to the actual database (Denodo/Redshift/SFDC/Oracle etc.). Maybe we should use the official DB/API names? It would be a bit more complicated: 
`{“config”:”databases” : {"denodo": {“denodo_prod” : {“dsn”: ”some_engine_str”}}, {"denodo_dev": {"dsn": "other_engine_str"}}`

**Comment by acivitillo** [comment]
Yes that makes sense

**Comment by malinaa96** [comment]
For me it's also great, we've already talked with Michal about it. The only concern that I have is that we use engine string in most of our classes and functions so this would be a big change to put it in the Config. I would wait a bit until everybody get used to the Config class and then add the databases key.

**Comment by michalz92** [comment]
@malinaa96 makes sense, but you know people are using a 2 weeks old grizly (except Patrycja whom I forced to download the new one)? :p

**Comment by acivitillo** [comment]
We need to continue to 1) fix bugs in master; 2) develop 0.3 the way it should be.

So my point is if the above makes sense we need to add it to 0.3. Meanwhile if people find bugs in master then we fix those bugs.

No merging of 0.3 into master until we have fixed all that needs fixing and updated our docs. We definitely need better docs once 0.3 comes out, we can't continue to drive things w/o docs as then we have to waste our time reviewing broken workflows

**Comment by acivitillo** [comment]
Also we most li

**Comment by bing9** [comment]
Thank you!
