### ISSUE TITLE
engine issue in create_table

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#260]
in 0.3 need to remove the create_engine as the engine passed to create_engine is already an sqlalchemy engine

function create_table, module etl.py

**Comment by malinaa96** [comment]
@acivitillo `create_table` uses engine string not the connection. With this commit

https://github.com/kfk/grizly/commit/724c287886484acf5b2a42ba6f0c66c5d545682b

you will break the QFrame.

**Comment by malinaa96** [comment]
There was an error in `write_to` function not in `create_table`. I fixed it already.

**Comment by acivitillo** [comment]
ok can we close?
