### ISSUE TITLE
pushing directly to 0.3 branch

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#261]
@acivitillo @michalz92 recently you have been pushing directly the commits from your pc's to 0.3 branch. Is there a way to track this commits? So far I was just checking the pull requests and I knew what was going on, now I don't really know what you change.

It would be much easier for me to track the changes if you pushed to your branches and then use pull requests to 0.3.

**Comment by michalz92** [comment]
Well you can find it in commits section. I guess we should do it this way but we were too lazy. If we do this I guess we need to also remember to pull frequently (even every day if needed).

**Comment by acivitillo** [comment]
Yeah for me the issue is that I basically need to merge my branch each time. But I agree we should not commit directly to 0.3 going forward.

**Comment by malinaa96** [comment]
I didn't see the commits tab. With this i can track the changes.
