### ISSUE TITLE
print is true in get_sql in write_to etl.py function

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#262]
in 0.3 print needs to be set to false in this function because it's annoying to get the sql print out each time we do qf.to_table()

**Comment by malinaa96** [comment]
For me `get_sql` should return SQL not QFrame. With this it would make more sense, the tests will be easier to write  and we don't need to have print parameter at all. @michalz92 what do you think?

**Comment by michalz92** [comment]
Yup, the `get_sql()` function is a false promise, because you get a QFrame instead. I think `print(QFrame)` should print the SQL, and get_sql should get the sql (which you can then also print if you choose to, e.g. print(qf.get_sql()). However I think it's more intuitive to just do `print(QFrame)`.

**Comment by acivitillo** [comment]
I agree, I can make this change probably today. Are you ok with this proposal @malinaa96?

**Comment by malinaa96** [comment]
Yes, for me it's perfect

**Comment by acivitillo** [comment]
OK I pushed the changes in 0.3. You can try get_sql() returns sql and print(qf) prints sql. Closing this one.
