### ISSUE TITLE
Not clear how to relate orchestrate issues to workflows milestones

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#264]
@acivitillo
We can't add orchestrator issues to workflows milestones, even though they directly impact the timeline. Should we create two issues, one in grizly, and one in workflows?

**Comment by acivitillo** [comment]
If grizly development issue impacts a business timeline the business issue goes in the private repo and the corresponding grizly issue comes here. So yes 2 issues.

**Comment by michalz92** [comment]
Ok
