### ISSUE TITLE
Types from store.json to pandas and/or dask dataframes

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#268]
Fun fact, if you want to create a dask dataframe from multiple files you need to make sure those files have been stored all with the same column types. This is even more true if you use the **parquet** format instead of the **csv** one (parquet file size is 10% of csv so we should use parquet).

Question. Can we rely on the field *custom_type* attribute of our json file to infer python types? It seems that for in-memory representations we will either use pandas dataframes or arrow, when we transform a dataframe or arrow table to a csv or parquet we need to pass the types too.

**Comment by malinaa96** [comment]
Well, in `custom_type` you can store the type of the column that you want to define in Redshift when you create a new table, so they will be verified during saving the data in Redshift. If you want to be sure that the types are correct you can use `get_columns` function which returns list of names of the columns of the table and also can return types which are defined in database. We do it like
```python
from grizly import get_path, get_columns, QFrame

columns, types = get_columns(table='table', schema= 'schema', db='redshift', column_types=True)
json_path = get_path(...)
initiate(table='table', schema= 'schema', columns=columns, col_types=types, json_path=json_path)
```

**Comment by acivitillo** [comment]
Yes but the issue is that pandas has it's own types and dask too. So we need to be able to convert from those custom types to pandas/dask types.

**Comment by michalz92** [comment]
You can use SQLAlchemy dtypes in DataFrame. They work for Redshift (tested). We only need a conversion from data source dtypes to SQLAlchemy ones. For now we only use DataFrames to get SFDC data, so there would be one mapping to be done. So then you can do 
```python
df = SFDC().query().to_df(dtypes="source", dtypes_dialect="redshift")
# inside to_df()
df = response_to_df()
if dtypes == "source":
    _, source_dtypes = get_columns(dtypes=True)
    dtypes = convert_dtypes(source_dtypes , source_dialect="sfdc", output_dialect=dtypes_dialect)
    df.dtypes = dtypes
```
