### ISSUE TITLE
Create tests for QFrame methods, join, union

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#27]
Create tests for 
etl.py, 
utils.py, 
QFrame methods,
join,
union.

**Comment by malinaa96** [comment]
For now join tests on chinook.db won't be created for right and full outer joins due to following error : 

![image](https://user-images.githubusercontent.com/52569986/62948187-37ed4300-bde4-11e9-923a-f6dc816381e7.png)

**Comment by kfk** [comment]
@malinaa96 is there still an issue with chinook.db?

**Comment by malinaa96** [comment]
@kfk yes, it's not supporting right and full outer joins, but I'm making tests in other way in these cases - I'm just comparing the sql strings
