### ISSUE TITLE
Please clearly communicate breaking changes

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#272]
If your change e.g. breaks all workflows, please let me know... you can usually run any one sample workflow to check this. Or maybe we need a separate branch for the scheduler? 
@malinaa96 @acivitillo

**Comment by acivitillo** [comment]
I have added a changelog.md file in 0.3 to document all changes including the breaking ones:

We should update such file and send to the team when doing the 0.3 release in January.

![image](https://user-images.githubusercontent.com/54931660/71085089-fb1cc880-2196-11ea-9e04-5a456e63f545.png)
