### ISSUE TITLE
Fix env in status table

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#273]
Fix it so that prod workflows actually show as "prod".

**Comment by michalz92** [comment]
This requires to finally set up the prod environment, which I will do after the holidays. It will run on `master` branch, whereas dev will run on `dev` branch. This will require both environments to be maintained separately, but I think by now it's a must. They're very similar so it shouldn't be much work.

I think we should also use a separate Python env for both (grizly master and tested libraries for `master`; grizly dev versions and updated libraries for `dev`). We can use Poetry to handle dependencies and set up services/cron jobs to run the prod interpreter on `master` and the dev interpreter on `dev`.

**Comment by acivitillo** [comment]
I forgot, do we follow a different release model for the orchestrate parts of grizly?

**Comment by michalz92** [comment]
Hm, I didn't end up doing above due to Dask delays (;)). I'm not sure, but I make a lot of changes to orchestrate (almost every day), so it's very different than the rest of grizly.

**Comment by michalz92** [comment]
Moved to https://github.com/tedcs/workflows/issues/198 as it's an infrastracture issue.
