### ISSUE TITLE
Enhance aggregation function types + names

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#288]
Hi team,

There are two major needs on groupby, agg function:
1. Type

- [x]  "SUM", 

- [x] "COUNT", 

- [ ] "COUNTDISTINCT"

- [ ] "COUNTNONNULL"

- [ ] "COUNTNULL"

- [x] "MAX", 

- [x] "MIN", 

- [x] "AVG", 

- [x] "STDDEV" added in [Pull 287](https://github.com/kfk/grizly/pull/287)

![image](https://user-images.githubusercontent.com/8092455/72151695-2b781100-33a9-11ea-9300-c046e12b9da7.png)

2. Names

For each aggregation, we need to rename them into different column names.
Currently: `groupby(['fiscal_year','fiscal_month'])['sales'].agg('sum')`
Intended: `groupby(['fiscal_year','fiscal_month']).agg({'sales': 'sum', 'sales': 'avg', 'sales': 'stddev'})`
Column names will be sales_sum, sales_avg, sales_stddev

![image](https://user-images.githubusercontent.com/8092455/72151879-b5c07500-33a9-11ea-822b-244cd53f0cf0.png)

**Comment by bing9** [comment]
I just realized there is a workaround using assign():
`.groupby(['sq.part_key_id','sq.distribution_channel_code','sq.pricing_region_cde']).assign(
        max_minimum_order_quantity = "max(sq.minimum_order_quantity)", type='num').assign(
    min_minimum_order_quantity ="min(sq.minimum_order_quantity)", type='num').assign(
    stddev_minimum_order_quantity ="stddev(sq.minimum_order_quantity)", type='num')`

Thus, I think above requirements is a duplication then?

**Comment by malinaa96** [comment]
Hi! Thanks for your contribution. It's a great idea to extend the number of types of aggregation, thanks for adding `stddev`. I don't think that we need more `count` types though. If you take a look at Redshift documentation https://docs.aws.amazon.com/redshift/latest/dg/r_COUNT.html you can see for example that if you want to do `countdictinct` you should do 
```SQL
select count (distinct venueid) as venues from event;
```
so you can just do 
```python
.assign(venues='distinct vanueid', type='num', group_by='count')
```

**Comment by acivitillo** [comment]
Can we close @bing9 ?
