### ISSUE TITLE
Add EmailListener

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#291]
@pattrycja96 

We need a new class, `EmailTrigger` or `EmailListener`, that will trigger a workflow when an email is sent from BOBJ. To make this, I heard you've volunteered to write the following function using exchangelib (you can get inspiration from Email class):

- inputs: `def get_last_email(workflow_name, email_folder=None, email_address=None, email_password=None)
- `email_folder` and `email_address` are taken from `Config` if not provided
- if `email_folder` is None, then search the entire mailbox
- else look only inside the folder and find the latest email containing workflow name in subject (`if workflow_name in subject`)
- return the datetime of the latest email (None if not found)

It would be nice to have a new class `grizly.Mailbox`, and then used inside this function (e.g. `mailbox = Mailbox() \ folder = mailbox[folder] \ for message in folder: ...`)

@michalz92 
I need to implement this functionality inside the new `orchestrate.EmailListener` that should probably be a subclass of `Listener`, since we will also be writing the run dates to `listener_store.json` etc. If this is implemented as a subclass, then `Runner` shouldn't need any modifications.

**Comment by pattrycja96** [comment]
Hi @michalz92, please have a look and check if this is what you wanted ;)

```Python
def get_last_email(workflow_name, email_folder=None, search_email_address=None, email_address=None, email_password=None, config_key="standard"):

    if email_address is None:
        _validate_config(config=Config.data[config_key],
                        services='email')
        config = Config.data[config_key]
        email_address = config['email']['email_address']

    if email_password is None:
        _validate_config(config=Config.data[config_key],
                        services='email')
        config = Config.data[config_key]
        email_password = config['email']['email_password']
        
    if search_email_address is None:
        search_email_address = email_address

    BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter 
    credentials = Credentials(email_address, email_password)
    config = Configuration(server='smtp.office365.com', credentials=credentials, retry_policy=FaultTolerance(max_wait=60*5))
    account = Account(primary_smtp_address=search_email_address, credentials=credentials, config=config, autodiscover=False, access_type=DELEGATE)
    
    last_date = None
    
    if email_folder!=None:
        if account.inbox.glob('**/'+email_folder).folders!=[]: #checks if folder exists
            for date in account.inbox.glob('**/'+email_folder).filter(subject__contains=workflow_name).order_by('-datetime_received').only('datetime_received')[:1]:
                last_date = date.datetime_received

    else:
        for date in account.inbox.filter(subject__contains=workflow_name).filter(subject__contains=workflow_name).order_by('-datetime_received').only('datetime_received')[:1]:
                last_date = date.datetime_received
                
    if last_date is not None:
        d = last_date
        last_date = datetime(d.year, d.month, d.day, d.hour, d.minute, d.second, d.microsecond, d.tzinfo)
        
    return last_date
```

**Comment by michalz92** [comment]
Thanks, but you forgot to include imports, and also the `_validate_config()` function was not working, so I had to provide email_address and email_password to run it. Could you share the imports needed to run this?

**Comment by pattrycja96** [comment]
```Python
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
from exchangelib import Credentials, Account, Configuration, DELEGATE, FaultTolerance
from grizly.utils import get_path
from grizly.config import (
    Config,
    _validate_config
)
from datetime import datetime
```
For me ```_validate_config()``` is working but I have a bit older version of grizly.

**Comment by pattrycja96** [comment]
I've also checked searching in proper folder and it also works in subfolders but doesn't go to parent folder as we wanted.

**Comment by michalz92** [comment]
I've managed to make it work, but the workflow does not end properly (doesn't report status to Rds/mail).

**Comment by michalz92** [comment]
Added to `michal` branch; will merge to 0.3 once stable.
