### ISSUE TITLE
Build Crosstab class

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#295]
For now I didn't create any class - only added new file `crosstab.py` where I put the functions that I wrote to make subtotals on a DataFrame.

How does it work?
```python 
import pandas

d = {'id': [0, 0, 0, 0, 0, 0]
     , 'product':["toys", "toys", "toys", "toys", "books", "books"]
     , 'country':["italy", "sweden", "italy", "italy", "sweden", "sweden"]
     , 'customer':["siemsn", "abb", "abb", "te", "siemsn", "abb"]
     , 'sales': [3, 4, 1, 2, 3, 3]
     , 'orders': [1, 1, 1, 3, 2, None]}

df = pandas.DataFrame(d)
df
```
![image](https://user-images.githubusercontent.com/52569986/72987504-d0074380-3dea-11ea-9a80-02c7fbc9b2d0.png)
```python
from grizly import get_crosstab
from IPython.core.display import HTML

columns = ['id', 'product', 'country', 'customer']
values = ['sales', 'orders']
subtotals = ['id',  'country']
html = get_crosstab(df, columns, values, subtotals)
display(HTML(html))
```
![image](https://user-images.githubusercontent.com/52569986/72987546-e1e8e680-3dea-11ea-9b12-eac0177c5d5d.png)

**Comment by malinaa96** [comment]
I put all the stuff in one class `Crosstab` and also changed a bit the data structure. Now the subtotals are calculated separately so that in the future we ca also put the tables in Excel. Now it works like this

```python
from grizly import Crosstab
columns = ['id', 'product', 'country', 'customer']
values = ['sales', 'orders']

crosstab = Crosstab(df, columns, values)
crosstab
```
![image](https://user-images.githubusercontent.com/52569986/73558602-d2554780-4453-11ea-9384-8cbe2ff59865.png)

```python
subtotals = ['id', 'product']
crosstab = crosstab.add_subtotals(subtotals)

crosstab
```
![image](https://user-images.githubusercontent.com/52569986/73558505-9ae69b00-4453-11ea-819c-93f36eafe105.png)

**Comment by malinaa96** [comment]
I cleaned up a bit `Crosstab` attributes. Now we keep the basic data in `.content` and the subtotals in `.subtotals`. This way it's easier to perform some calculations. 

```python 
from grizly import Crosstab

columns = ['id', 'product', 'country', 'customer']
values = ['sales', 'orders']

crosstab = Crosstab().from_df(df, columns, values)
crosstab
```
![image](https://user-images.githubusercontent.com/52569986/73667842-33c02500-46a5-11ea-8528-c9923356b6a6.png)

```python
crosstab.content
```
```
{(0, 'toys', 'italy', 'siemsn'): {'sales': 3, 'orders': 1.0},
 (0, 'toys', 'sweden', 'abb'): {'sales': 4, 'orders': 1.0},
 (0, 'toys', 'italy', 'abb'): {'sales': 1, 'orders': 1.0},
 (0, 'toys', 'italy', 'te'): {'sales': 2, 'orders': 3.0},
 (0, 'books', 'sweden', 'siemsn'): {'sales': 3, 'orders': 2.0},
 (0, 'books', 'sweden', 'abb'): {'sales': 3, 'orders': 0}}
```

I added also some methods like
- formatting and styling of the numbers
- operations: sum avg, count
- append rows and columns

I placed all of these in one notebook https://github.com/kfk/grizly/blob/0.3/notebooks/crosstab.ipynb

![image](https://user-images.githubusercontent.com/52569986/73668457-2b1c1e80-46a6-11ea-9545-1ca72ab28094.png)



## What needs to be done next?

- multicolumns option like this

![image](https://user-images.githubusercontent.com/52569986/73668618-674f7f00-46a6-11ea-9b98-aa7c99ce320d.png)

- methods to perform operations on the columns or rows

- some global styling for the table (content and subtotals or separately) but I still don't know where should I put it, maybe we will just use CSS

**Comment by malinaa96** [comment]
I added option to append header with a new row. I had to create a new method `.append_header` but in the future this can be a part of `.append` method

```python
crosstab.append_header(['Dimensions', 'Dimensions', 'Dimensions', 'Dimensions', 'Measures', 'Measures', 'Measures'], 0)
```
![image](https://user-images.githubusercontent.com/52569986/73755330-2ae35800-4766-11ea-8b18-e24a758fc16f.png)


I tried to add some global styling on the table with css class but I have some problems with jupyter - it seems that he does not allow me to change styling of the table 

![image](https://user-images.githubusercontent.com/52569986/73755167-e952ad00-4765-11ea-8496-6289d99b5712.png)


We need to find a way how to force him to use our css.

## What needs to be done next?
- [ ] Improve subtotals part - it's hard to do the grand totals now as we need an additional columns for this
- [ ] Figure out where to put css and how to use it in jupyter
- [ ] Add concat/merge function
- [ ] `.from_df` method generates good crosstab only if the dataframe doesn't have duplicated rows in - we need to add an option to aggregate duplicates
- [ ] Add remove method
- [ ] Add rename method
- [ ] Improve `.append` method so that we can add a row or a column in any place
- [ ] Rename `.map` method to `.apply_map` and save the output of the mapping functions not the functions

**Comment by malinaa96** [comment]
I added remove and rearrange methods. We really miss easy calculations on the columns or on the rows especially when we already have subtotals and this should be improved quickly. 

We also need to change the way of editing header - for now we only have  `.append_header` which only append header with a row so it's definitely not enough.

**Comment by acivitillo** [comment]
Let's start mapping out the api, implemented or not.

```python
ct = Crosstab().from_df()
ct.assign(test = "sales * orders")
ct.rows([country], grandtotal = True, subtotals = True) # used to be dimensions in old Crosstab
ct.columns([customer], grandtotal = False, subtotals = False) 
ct.values()
```

**Comment by malinaa96** [comment]
`Crosstab` is quite stable right now - all other functionalities mentioned in this issue can be moved to smaller issues as soon as there will be a need to improve this class or we can reopen. Closing for now.

**Comment by michalz92** [comment]
@malinaa96 Can this be closed now?
