### ISSUE TITLE
EC2 MVP

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#296]
@acivitillo 

Plan for MVP:

- [ ] Figure out how to run control_check workflows
- [ ] Set up workflow_runner as a cron job to run e.g. every 30 minutes
- [x] Move logs from stdout to file
- [x] Change logs' timezone to UTC
- [ ] Test: 
    - [ ] c2s
    - [x] a big workflow  - tested GCS Frozen Cost V (run time: 17min vs VM 2h:40min)
    - [ ] run for a long time
    - [ ] failure recovery
    - [x] multiple workflows at the same time  - tested `Sales Daily News` + `Sales Daily New EMEA` +  `GCS Frozen Cost V`
- [ ] Add the rest of the workflows
- [ ] Fix known bugs:
    - [ ] sheduled workflows are submitted on each `workflow_runner` run, e.g. if the runner runs 20 times/hour, each scheduled workflow will be submitted 20 times
    - [ ] `graph key not found -- plugin failed` in `transition()` -- does not break anything so may be pushed after MVP? or maybe this is why some states seem to be missing?

**Comment by acivitillo** [comment]
I think this issue should be in workflows repo...

**Comment by michalz92** [comment]
Moved
