### ISSUE TITLE
Add  write_to() method in QFrame

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#30]
This new method will save the results in somewhere in the database.

**Comment by malinaa96** [comment]
For now we have two methods:

* to_rds() used to save data in Redshift (uses csv and s3 files) - good for big tables
* to_sql() used to save data in any database (uses pandas.read_sql()) - good for small tables

Do we need anything more?

**Comment by malinaa96** [comment]
We still need write_to() method as it will work as INSERT INTO, so it can only be used as from Redshift to Redshift - it won't work with Denodo.

**Comment by pattrycja96** [comment]
Write_to() method is ready to use. It works as INSERT INTO and uses data from qframe to put them into table using the same engine. Testing in Redshift has ended successfully.
