### ISSUE TITLE
add qf  to_parquet

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#313]

**Comment by krzyzanowskik** [comment]
Hi Alessio,

dimension_network_user in master branch might be a good starter. In JSON file all columns have defined type and it is only 75k rows.

https://github.com/tedcs/workflows/tree/master/workflows/dimension_network_user

**Comment by michalz92** [comment]
@krzyzanowskik I think all columns in every `QFrame` have their types defined, just some of them are VARCHAR(500). We should utilize `get_columns()` wherever possible to minimize the number of such big columns.
@acivitillo please make sure it won't break `grizly.S3` methods as I'm using them already in some workflows.

**Comment by acivitillo** [comment]
I am having issues with the COPY statement. It seems we need a iam_role to load parquet files into rds. Sent email to subash.

[Code: 500310, SQL State: XX000]  [Amazon](500310) Invalid operation: COPY from this file format only accepts IAM_ROLE credentials.
Details: 
 -----------------------------------------------
  error:  COPY from this file format only accepts IAM_ROLE credentials.
  code:      8001
  context:   
  query:     0
  location:  xen_copy.cpp:151
  process:   padbmaster [pid=14616]
  -----------------------------------------------;

**Comment by acivitillo** [comment]
This one is done and pushed. Note you need to use BIGINT and not INTEGER in your qframe custom data types. Parquet files have much stricter data types than csv ones, so expect some conflicts between your parquet types and your db types.
