### ISSUE TITLE
Improve email triggered workflows' notifications

### ISSUE THREAD

**Issue by vperluzzo** [kfk/grizly#318]
@michalz92 
Can we have the time when the notification was received?
At this point I don't know if the notification was received at 10 something (pretty late!) or if it was around 7 something and we just didnt have available workers for around 3 hours.

![image](https://user-images.githubusercontent.com/51827647/75756681-5a6b8d00-5d31-11ea-80f6-7c68c9f758de.png)

**Comment by michalz92** [comment]
The notifications are in acoe_team mailbox, but I'll check if I can easily add it to the notification.

**Comment by michalz92** [comment]
Yeah, it's not easy (we actually don't have any of above info on EC2 for now). But on EC2 workflows are submitted immediately. I'll add workflow start time and you can assume it's the time the notification was received.

**Comment by acivitillo** [comment]
Can we close?
