### ISSUE TITLE
Improve QFrame editing

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#32]
We need more methods to edit QFrame like:
-> hide(), unhide() (to change the selected fields),
-> change_type()
-> edit_expression()
-> change_field_order()
and so on.

So far we have rename() to change the name and remove() to remove a field.

Or instead of creating new methods we should think about other way to edit QFrame.

**Comment by kfk** [comment]
Could something like this help: http://www.smartjsoneditor.com/

So editing the json directly?

**Comment by malinaa96** [comment]
I added save_json method to save QFrame data in json file. We can edit it with editor
![image](https://user-images.githubusercontent.com/52569986/62949634-d7133a00-bde6-11e9-8c04-dea64e91cb98.png)

the data in jupyter lab editor is not very easy to read
![image](https://user-images.githubusercontent.com/52569986/62949793-235e7a00-bde7-11e9-8185-368c7a7bc2cf.png)

but we can edit this json file with any other json editor, save it and use read_json method to load the data to QFrame.
