### ISSUE TITLE
16_mar_2020 grizly call talking points

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#321]
@michalz92 and @malinaa96 please add here things to discuss in our next grizly meeting.

**Comment by malinaa96** [comment]
We should discuss `SQLDB` class - attributes, methods and so on. For now I just placed there all the functions that we already had
Code: https://github.com/kfk/grizly/blob/0.3/grizly/tools/sqldb.py
Docs: https://grizly-docs.readthedocs.io/en/0.3/content/api_SQLDB.html
Sample notebook: https://github.com/kfk/grizly/blob/0.3/notebooks/sqldb.ipynb

**Comment by acivitillo** [comment]
* 0.3 release
