### ISSUE TITLE
Create class HTMLGenerator

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#332]
## Summary
We need a class that would help as with generating html files using rst, latex or generating pdfs. Our idea is to load a template file to HTMLGenerator, where we will have blocks. One block corresponds to one page in pdf file and inside each block we could have variables. Then when we want to generate a pdf, we specify which blocks we want to use. 

## api
- attributes
    - file_dir
    - blocks
    - variables
- methods
    - from_rst
    - from_html
    - load_variables  [similar to jjina2.render]
    - to_html
    - to_pdf

## Example
We have `template.html` file and `vars.json` file:
```
template.html
    {% block summary_mtd %}
    {% block summary_qtd %}
    {% block daily_det %}
vars.json
    {"calendar_date": "02/27/20",
    "mtd_tab": [html table],
    "qtd_tab": [html table],
    "daily_det_tab": [html table],}
```
We generate pdf including only two blocks `summary_qtd ` and `daily_det`
```python
htmlgen = HTMLGenerator().from_html('template.html')
htmlgen.load_variables('vars.json')
htmlgen['summary_qtd', 'daily_det'].to_pdf('output.pdf')
```

We would store the variables in json file as this would be the output of each report. With this solution we can run the workflows separately, upload json to S3 if the report is correct and read it on the website.

**Comment by malinaa96** [comment]
@acivitillo does it make sense for you? We are not sure yet how this would work with the website, probably we need another class which would read folders with the website structure. What do you think?

Also, could you add Piotr to grizly contributors so that I can assign him too?

**Comment by acivitillo** [comment]
You want to have this structure first (similar to sphinx):

```
|-- content
     |-- is_dbb.rst
     |-- eng_dbb.rst
```

And then you want to do:

```python
html_table = Crosstab().to_html() #some crosstab
htmlgen = HTMLGenerator().from_content(content=content_path,  data={html_table:html_table})
htmlgen['summary_qtd', 'daily_det'].to_pdf('output.pdf')
```

The html templates should be part of grizly not user defined. User should only define the content in .rst files. This is how the acoe site works.

**Comment by malinaa96** [comment]
Ok but `is_dbb` and `eng_dbb` are two separate reports if you want to read them both then still later we have to separate them somehow. So either we have a method like for example `get_report` and then we do
```python
htmlgen = htmlgen.get_report('is_dbb')
htmlgen['summary_qtd', 'daily_det'].to_pdf('output.pdf')
```
or we automatically add a perfix to each block that is in the template for example
```python
htmlgen['is_dbb_summary_qtd', 'is_dbb_daily_det'].to_pdf('output.pdf')
```

**Comment by acivitillo** [comment]
We have report -> pages right? So each page could have a different template?

```python
html_table = Crosstab().to_html() #some crosstab
htmlgen = HTMLGenerator().from_content(content=content_path,  data={html_table:html_table}, ,template="is_dbb") #add template here
htmlgen['summary_qtd', 'daily_det'].to_pdf('output.pdf')
```

But then again, how is is_dbb different from emea_dbb in terms of templates?

**Comment by malinaa96** [comment]
Well they differ a bit with the captions and for example in IS DBB we have footer on some pages or other comments. These could be also variables but for me it's more like a template part cause it won't change.

**Comment by acivitillo** [comment]
I understand but if you look at the .rst file you can add captions, titles etc. as declarations. You can construct the content in .rst and do the templates in html/css

**Comment by pmarekk** [comment]
We are changing the approach, so after we finish with https://github.com/kfk/grizly/issues/380 and related issues, we will create a separate and proper issue for generating web page.
