### ISSUE TITLE
Closing and testing 0.3

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#346]
Today me, @michalz92 and @pmarekk tested 0.3, we found some bugs and fixed them and for now it works for us. We scheduled a meeting with Mateusz for Monday to test on his workflows.

**Comment by michalz92** [comment]
Email notifications seem to not work for local runs (at least for Piotr).

**Comment by pmarekk** [comment]
After changing proxy in environment variables email is working.

![image](https://user-images.githubusercontent.com/56957588/76742363-45e7b580-6771-11ea-847e-1ef68cfbc186.png)

**Comment by malinaa96** [comment]
That's because the proxy is read in the order 
`proxy specified in the parameter -> proxy in env vars -> proxy in config` 
if it's not found in previous step then it goes further. We have to make sure that we have the right proxy everywhere.

**Comment by malinaa96** [comment]
We tested 0.3 with Kamil and for now it works for one workflow - Kamil will let us know in case of any errors with other workflows.

**Comment by malinaa96** [comment]
I merged 0.3 with master. I had to resolve some conflicts, so @acivitillo @michalz92 please pull master branch to check if everything works and if yes then I will publish new release and we can start working on 0.4

**Comment by malinaa96** [comment]
Ok, I hope it works for you, I released 0.3, we can start working on 0.4
