### ISSUE TITLE
Bug in S3().to_rds()

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#347]
@malinaa96 there is a bug with S3().to_rds(). `replace` does not do a `delete from schema.table`, it looks like it's doing a union, so this code

```python
s3.to_rds(table="ac_github_issues", schema="sandbox", if_exists="replace")
```

duplicates data in the rds table.

**Comment by malinaa96** [comment]
Did you pull the latest version? The issue was this https://github.com/kfk/grizly/issues/341 but I fixed it yesterday, now I see that if the table doesn't exists then `s3.to_rds` doesn't work but I fixed it just now and I will push the fixes in a minute.

**Comment by malinaa96** [comment]
Ok now it also creates table if it doesn't exist (https://github.com/kfk/grizly/pull/349), I checked replace option and it works. You can check it and close if it works for you.

**Comment by acivitillo** [comment]
works now
