### ISSUE TITLE
Filter expressions

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#35]
If we want  group by the expression then the alias of the expression can't be the same as any column name which we are using. For example:

-> SELECT customer, CASE WHEN fiscal_year=2019 AND billings>0 THEN 2019 ELSE NULL END AS fiscal_year, SUM(bookings) FROM orders GROUP BY customer, fiscal_year

 Returns an error which says that we should also add "billings" to group by clause. 

Therefore we need a filter on expression so that the alias is not the same as the name of the column in the table.

**Comment by kfk** [comment]
Could you explain this a bit more? If I read this:

`SELECT customer, CASE WHEN fiscal_year=2019 AND billings>0 THEN 2019 ELSE NULL END AS fiscal_year, SUM(bookings) FROM orders GROUP BY customer, fiscal_year`

I think the column `billings` should at least be in the select as `SUM(billings)`, or? Here is the issue I see. Are we really doing `billings>0` in the CASE or are we doing effectively `SUM(billings)>0`?

I don't know, you need to see if the SQL does the `group by` before any `select` formula. If `group by` is always first then you need to automatically add SUM(billings) in that example or we need to ask the user to do a proper `group by` first which includes `billings`

Please check. I think we need to simply add a `group by` does not include `billings` message and we can close this.

**Comment by malinaa96** [comment]
Maybe for now it's not a big issue I will return to this in the future. Let's just keep that in mind.
