### ISSUE TITLE
boto3 throws connection errors if HTTPS_PROXY is not specified in env variables

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#356]
boto3 doesn't allow to pass the proxy in the configuration file and it only reads environmental variables, so when somebody doesn't have HTTPS_PROXY and HTTP_PROXY in env variables then it throws connection errors. As a temporary solution if HTTPS_PROXY is not found I'm setting it the same as HTTP_PROXY and the same with HTTP_PROXY.

We could read the proxies from our config file but as long as we want to do `Config.from_s3()` we cannot use our config in S3 class, so either we resign from `Config.from_s3()` and use one config for all classes in grizly or we have to find some other solution how to pass proxy to S3 class.

@acivitillo @michalz92 share your ideas here or we can talk about it on the next grizly meeting

**Comment by michalz92** [comment]
I'd put env variables in a config file, too. You can eg. use python-dotenv to read these env variables into the system on Config init (it uses a `.env` file by default).

**Comment by acivitillo** [comment]
You can add env variables also in the dockerfile

**Comment by michalz92** [comment]
I think .env is more general because it will also work for people that run grizly without Docker. And Docker can also read .env files.

**Comment by malinaa96** [comment]
I think I will just read the proxy from config file cause when I get proxy errors I never know which proxy was used. With this solution I will always check the config first.
