### ISSUE TITLE
remove old branches

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#365]
@pmarekk @michalz92 could you remove these branches?

![image](https://user-images.githubusercontent.com/52569986/77733529-4d2b8080-7007-11ea-8d48-23f9fce8e8c4.png)

**Comment by pmarekk** [comment]
Branch has been successfully removed.

**Comment by michalz92** [comment]
Done. Why are we keeping 0.2 though?

**Comment by malinaa96** [comment]
We kept it because of the docs versioning, but now we use releases for this

![image](https://user-images.githubusercontent.com/52569986/77739651-2a529980-7012-11ea-8a66-e5c7b6c42ae1.png)

so we can remove them.

Thanks!
