### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#37]
For now we are using only from_dict and read_excel methods which are not very easy to use especially when we have many columns. Also we want to avoid creating excel files. In the future it would be better to keep all data in json file or in database.

**Comment by kfk** [comment]
@malinaa96  keep in mind excel files can be shared with business users, json cannot. So maybe we should think of having a function that translates Excel into json and then our team can work on the json directly?

**Comment by kfk** [comment]
We will use jsoneditoronline for this. I don't see us using widgets any time soon (next 2-3 months). So let's close and re-evaluate later.
