### ISSUE TITLE
QFrame().to_rds() does not create table when using parquet extracts

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#376]

**Comment by malinaa96** [comment]
We can use `pyarrow` for this

```python
import pyarrow.parquet as pq

tab = pq.read_table("s3_loads/tasks_issues.parquet")
```

Will do it tomorrow

**Comment by michalz92** [comment]
We can try using `turbodbc` to upload from `QFrame` to S3:
https://turbodbc.readthedocs.io/en/latest/pages/getting_started.html

**Comment by michalz92** [comment]
So the full workflow would be SQL -> QFrame -> pyarrow table (in-memory) -> S3 -> Redshift. This way we should be able to preserve the right data types, as pyarrow is much more flexible than pandas in that regard. So we can already define the right datatypes in the pyarrow table. And the `.parquet` files are written to S3 by S3, not by us, so we don't create any side effect files, which means we don't impact I/O, which means the workflows should be much faster (as long as we're within memory limit).

**Comment by malinaa96** [comment]
I fixed `S3.to_rds` so that it creates table like `parquet` file. This one works
```python
from grizly import S3

s3 = S3(file_name="tasks_issues.parquet", s3_key="data_loads/github/")
s3.to_rds(table="parquet_test", schema="sandbox", types={"milestone_description": "VARCHAR(1000)"})
```
I'm reading `parquet` file with `pyarrow` and then look for the right type using this dict
```
dtypes =  {"bool": "BOOL",
     "int8": "SMALLINT",
     "int16": "INT2",
     "int32": "INT4",
     "int64": "INT8",
     "uint8": "INT",
     "uint16": "INT",
     "uint32": "INT",
     "uint64": "INT",
     "float32": "FLOAT4",
     "float64": "FLOAT8",
     "date": "DATE",
     "string": "VARCHAR(500)",
     "timestamp.*\s*": "TIMESTAMP",
     "datetime.*\s*": "DATETIME"}
```
I'm not really sure if this includes all `pyarrow` types but I can't find the full list. If the type is not found I just put `VARCHAR(500)`.
