### ISSUE TITLE
Add chunksize parameter to QFrame

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#388]
```python
# queries the table in chunks and writes the chunks to a single DataFrame
df = qf.to_df(chunksize=100_000)
df.to_csv(f"df.csv", index=False)
```

We also need an iterator though chunks, eg.:
```python
# queries the table in chunks and writes the chunks to multiple DataFrames
dfs = qf.to_dfs(chunksize=100_000)
for i, df in enumerate(dfs):
    df.to_csv(f"df_{i}.csv", index=False)
```

Eventually, this should have a different implementation for each database (eg. Postgres supports server-side cursor), but for now let's just use `OFFSET x LIMIT y`

**Comment by michalz92** [comment]
This is done. We also need an iterator though chunks, eg.:
```python
for chunk in qf.chunks:
    chunk.to_df()
```

**Comment by michalz92** [comment]
```
# Dask
@dask.delayed
def get_qf_chunk(qf, chunksize):
    return qf.fetchmany(chunksize)

@dask.delayed
def qf_to_df(qf):
    return qf.to_df()

while True:
    chunk = get_qf_chunk(qf, chunksize=100_000)
    df = qf_to_df(chunk)
````

I don't know how to know when to terminate the loop though... a) if dask could return an iterator, it would be easy

**Comment by michalz92** [comment]
Another way is a brutal:
```python
chunksize = 100_000
offset = 0
limit = chunksize
while True:
    qf_chunk = qf.offset(offset)
    qf_chunk = qf.limit(limit)
    df = qf_to_df(qf_chunk)
    ...
    offset += chunksize
    limit += chunksize
```

**Comment by acivitillo** [comment]
Yes, but I would do:

```python
qf_chunk = qf.limit(limit, offset=offset)
```

That way it's just an enhancment of qf.limit().

**Comment by malinaa96** [comment]
What about the json file? 
![image](https://user-images.githubusercontent.com/52569986/79446405-745de800-7fde-11ea-9f46-3bb386d2a2ce.png)
`offset` would be inside `limit` key or it should be a new key?

**Comment by acivitillo** [comment]
I think offset should be inside limit.

**Comment by michalz92** [comment]
But that depends on whether LIMIT is required with OFFSET. If it's not, it doesn't make sense. But I'm not sure.

**Comment by malinaa96** [comment]
@acivitillo in Redshift for example we can use `offset` without `limit` - they don't have to occur together, I would stick to `QFrame.offset()` method.

**Comment by michalz92** [comment]
Ok, I've added `qf.offset(offset)`, `qf.window(offset, limit)`, and `qf.cut(chunksize)`. Window generates a window with `limit` of rows and cut cuts the qframe into many smaller qframes, each having `chunksize` rows in the sql, eg. `qfs = qf.cut(chunksize=100000)`

**Comment by acivitillo** [comment]
Looks good. Can we close?
