### ISSUE TITLE
[Bug] q_frame.get_dtypes() slow

### ISSUE THREAD

**Issue by bing9** [kfk/grizly#397]
Hi Team,

As discussed, `q_frame.get_dtypes()` is very slow comparing to `q_frame.get_fields()`.

After below work around it is much faster:
`q_frame.create_sql_blocks() `
`q_frame.data["select"]["sql_blocks"]["types"]`

**Comment by malinaa96** [comment]
Fixed on `dev` branch, will be available in `grizly 0.3.3`, thanks!

**Comment by bing9** [comment]
Thanks!

Could I be added to grizly contributor group?

Regards,

Bing

**Comment by malinaa96** [comment]
Aren't you already in this group? :)
