### ISSUE TITLE
grizly qf create_table should not be deprecated in 0.4

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#411]
Please have a look. The functionality of qf.create_table() cannot be replicated by SQLDB().create_table() at this point. So the below warning is incorrect.

![image](https://user-images.githubusercontent.com/54931660/81266471-0f2d6d80-9045-11ea-9d04-9ca64ba5769a.png)

**Comment by malinaa96** [comment]
But why do you want to create a table? `QFrame.to_table` method will create a table for you if it doesn't exists. 
In case of saving `QFrame` records to s3 and then from s3 to RDS or Aurora the tables should also be created if they don't exist based on types from s3 or passed in dictionary.

**Comment by acivitillo** [comment]
Well I assume the qf.create_table() creates the table based on the queries.json column custom types? In this example I would like to control the types created and the qframe seems to be the best option for doing so.

**Comment by malinaa96** [comment]
Ok if this method makes our live easier then we can keep it.

**Comment by malinaa96** [comment]
Done
