### ISSUE TITLE
feature qf.pivot()

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#420]
@malinaa96  as discussed find pseudo code below:

```python
def qf_pivot(self_qf, columns=["col1"], value=["val1"]):
    #Generate column values to pivot
    _add_dates = add_dates.copy()
    _add_dates.select([column])
    _add_dates.groupby([column])
    column_values = _add_dates.to_df()[column]
    
    #Translate
    for column in column_values:
        col_name = f"m{column}"
        add_dates.assign(**{col_name:f"case WHEN cfm={column} then remaining_quantity else 0 end"})
    
    #Aggregate on *dim* fields
    add_dates.groupby(["sq1.material_number", "sq1.plant"])[months_str].agg("sum")
```

**Comment by malinaa96** [comment]
Done with https://github.com/kfk/grizly/pull/429. For now there is only option to pass one column to `values` parameter and you can only do sum aggregation. We can improve it later.

You can check [docs](https://grizly-docs.readthedocs.io/en/0.3.5/content/api/grizly.QFrame.html#grizly.QFrame.pivot) and [tutorial](https://grizly-docs.readthedocs.io/en/0.3.5/content/api/qframe.html#Pivot) for more details.
