### ISSUE TITLE
add indented row dimensions to Crosstab()

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#422]
Currently Crosstab() does not support indentation so if we use many dimensions the report can get very wide.

I think we need something like this: https://community.powerbi.com/t5/Desktop/Adding-indentation-and-hierarchy-to-a-list-of-project-tasks/td-p/441331

It is a change of the html table generator.

**Comment by acivitillo** [comment]
Here is a proposal in html. Click "search" to see the file

https://retool.tycoelectronics.net/apps/development/S3%20for%20ACOE?s3_path=workstreams/grizly

**Comment by malinaa96** [comment]
I added indented view with https://github.com/kfk/grizly/pull/423

Here is a comparison between two views

![image](https://user-images.githubusercontent.com/52569986/81958656-94e58600-960e-11ea-995b-b8c00f43d7f2.png)


So the grand total would probably go at the bottom.
