### ISSUE TITLE
Remove the need for calling Config().from_json() explicitly in all workflows and in all modules

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#425]
**What does this bring**
- allows users to skip the config boilerplate we currently have to copy-paste to each workflow:
```
from grizly import Config
config_path = get_path(".grizly", "config.json")
Config().from_json(config_path)
```
- simplifies other modules using config under the hood
- will simplify the logging stuff in workflows and other modules

With this change, the user will not have to bother with config at all. Grizly will read the config from the standard location (`~/.grizly`) and use it under the hood. We can also allow a global config if needed (it's a standard practice to have global and user configs, but I haven't seen such use case in grizly yet). Global config could be put inside `/etc/grizly`, as is the standard practice.

**Future features this allows**
- logging: this will allow for handling logging in a standard way, ie. setting a package-wide logger instead of duplicating effort in each class (`QFrame`, `S3`, `SFDC`, `Extract`, etc.). This will set the logger to `distributed.worker`; users still need to add the name of the workflow manually at the start of their workflow: `my_logger = logger.getChild(workflow_name)`.

**Implementation**
`configuration.py`:
```python
DEFAULT_CONFIG = os.path.join(os.path.dirname(__file__), "config.toml")
USER_CONFIG = os.getenv("PREFECT__USER_CONFIG_PATH", "~/.prefect/config.toml")


class Config():
    # a dict-like object
    pass


def load_configuration(path: str,  user_config_path: str = None) -> Config:
    pass


config = load_configuration(
    path=DEFAULT_CONFIG,
    user_config_path=USER_CONFIG
)

# DEFAULT_BACKEND = "dask.distributed"
# logger = configure_logger(DEFAULT_BACKEND)
```

`__init__.py`:
```python
from grizly.configuration import config
# from grizly.configuration import logger
```

**Comment by malinaa96** [comment]
Ok not sure if this will be enough for you but I right now you don't have to do 
```python
from grizly import Config
config_path = get_path(".grizly", "config.json")
Config().from_json(config_path)
```
in every workflow as long as you store config file in `get_path(".grizly", "config.json")` or you specify the right path in environment variable `GRIZLY_CONFIG_FILE`.

**Comment by michalz92** [comment]
It works great!
