### ISSUE TITLE
do we really need this module: html5print?

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#431]
guys we need to be mindful of the installs we add to requirements. It is a lot of added complexity when we add new libs. Let's make sure the new libs are worth the added complexity.

@malinaa96

**Comment by pmarekk** [comment]
I have added this lib at the beginning of page classes creation. I was using it for see html output more clearer. I wasn't aware that it contains that much links to other libs. I will remove it, because it doesn't affect code creation.

**Comment by pmarekk** [comment]
Changes applied to new branch 0.3.6. It will be part of next release.
