### ISSUE TITLE
to_table() doesn't work with if_exists=fail option

### ISSUE THREAD

**Issue by acivitillo** [kfk/grizly#443]
I have to use "replace" because "fail" gives a "table already exists" error. 

```python
qf_final.to_table(schema="sandbox", table="current_inventory_pivot", if_exists="replace")
```

**Comment by malinaa96** [comment]
Ok but why you think this is a bug?

**Comment by malinaa96** [comment]
I mean the option `if_exists='fail'` raises error and is default on purpose - the user have to confirm that he wants to delete existing data first. I followed the logic from here https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html. 

The only difference is that the option `'replace'` doesn't drop the table but it only cleans the records. We will add additional option `'drop'` (https://github.com/kfk/grizly/issues/441) in next releases.
