### ISSUE TITLE
Deprecate engine string and remove sqlalchemy from requirements

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#455]
W should start using `dsn` instead of `engine_str` parameter. This will probably take some time so the first step is to deprecate this parameter.

**Comment by malinaa96** [comment]
All tools are good. I didn't remove `engine_str` parameter completely but added deprecation warnings. @michalz92 I think you are still using sqlalchemy in `orchestrate.py` could you clean it up?

**Comment by michalz92** [comment]
Removed.
