### ISSUE TITLE
Change SQLDB class configuration

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#459]
Right now the configuration for SQLD clas looks like

```
"sqldb": {
	  "redshift": "mssql+pyodbc://redshift_acoe",
	  "aurora": "mssql+pyodbc://aurora_db"
	  }
```

as we want to move away from sqlalchemy it's doesn't make sense to keep engine string any more. We will use dsn and for each dsn there should be specified database and dialect so the config will look like

```
"sqldb": {
	  "redshift_acoe": {"db": "redshift", "dialect": "postgresql"},
	  "aurora_db": {"db": "aurora", "dialect": "postgresql"}
	  }
```

Also the `db` parameter won't be nessesary as long as it will be sepfified in the config so we will call SQLDB class by doing

```python
SQLDB(dsn="redshift_acoe")
```

**Comment by malinaa96** [comment]
Done in `0.3.6` with

You can still use `db` parameter but it's deprecated and I will remove it later.

![image](https://user-images.githubusercontent.com/52569986/86378567-16aa7500-bc8a-11ea-96c4-48738908f920.png)

So instead of doing for example
```python
SQLDB(db="redshift")
```
we should do 
```python
SQLDB(dsn="redshift_acoe")
```
and dsn `redshift_acoe` should be specified inside config file.

For now the configuration is hard coded as a dictionary with all dsn that are used by ACOE. I will fix it in next release cause this will require changing everybody's configs.

**Comment by bing9** [comment]
Hi Kasia,

I'm using sqldb.engine_str to feed into QFrame(engine = sqldb.engine_str). If this attribute is taken out from SQLDB class, where should I point to the current active engine (instead of manually point to QFrame everytime)?

Thank you!

Bing

**Comment by malinaa96** [comment]
Hello,

Instead of `engine` or `engine_str` you can pass the `dsn` parameter both in SQLDB and in the QFrame. You can also pass SQLDB class to QFrame so you can do either
```python
sqldb = SQLDB(dsn="DenodoPROD")
qf = QFrame(dsn=sqldb.dsn)
```
or
```python
sqldb = SQLDB(dsn="DenodoPROD")
qf = QFrame(sqldb=sqldb)
```
or you can just do
```python
qf = QFrame(dsn="DenodoPROD")
```

of course this will work for grizly 0.3.6 which will be released I think this or at the begging of next week :)
