### ISSUE TITLE
QFrame config file path

### ISSUE THREAD

**Issue by kfk** [kfk/grizly#64]
Currently we must be in the python folder in order to use grizly:

`%cd -q \\pln60fs100\TE_KRK\ACOE\Internal\4_Docs\Python`

But this is not a good idea as it's depending on the local user environment.

Instead we should import the default file from:

`C:\\Users\\networkId`

This path is easy to find with python:

`import os
os.environ['USERPROFILE']`

So the idea is that the user adds a conf file in:

`C:\\Users\\networkId\\.grizly\\config.json`

Similar as the user has to modify the jupyter config file:

`C:\\Users\\eg013949\\.jupyter\\jupyter_notebook_config.py`

Furthermore I propose to add a cwd (current working directory) inside the api.py, this means we could do:

`
from grizly import QFrame, cwd
print(cwd)

-> C:\\Users\\networkId
`

As we move towards github we can leverage the user folder more, we won't be using shared drives as much in the future, hence using a local folder for user projects might make sense

**Comment by malinaa96** [comment]
I changed the script. Now if you want to use grizly you have to create a folder .grizly inside 
`C:\\Users\\networkId`

To create a folder that begins with a dot you have to add a dot at the end also 
![image](https://user-images.githubusercontent.com/52569986/63678651-e71c1800-c7ef-11e9-9a60-087cd9476353.png)

After creating a folder copy `etl_config.py` file from 
` \\pln60fs100\TE_KRK\ACOE\Internal\4_Docs\Python`
and paste it in 
`C:\\Users\\networkId\\.grizly`

I also added cwd. It's just a string taken from 
 `os.environ['USERPROFILE']`
and should return

-> C:\Users\networkId
