### ISSUE TITLE
Start documenting on readthedocs

### ISSUE THREAD

**Issue by kfk** [kfk/grizly#65]
We should create a pandas like documentation with sidebar here:

https://docs.readthedocs.io/en/stable/#

We can start with a sidebar that looks like this:

Getting Started -> Paste the readme here
QFrame
   read_json
   read_excel
   etc.

**Comment by acivitillo** [comment]
@malinaa96 @michalz92 I was able to get docs loaded on readthedocs: https://grizly-docs.readthedocs.io/en/remove_win32/content/QFrame.html#i-o

I have also removed win32

@malinaa96 and @pattrycja96 could you test the grizly from the branch **remove_win32** and let me know if this works for you? I mean especially the Excel class and the *get_value()* method

@malinaa96, for your information, I have removed the *open()* method from the Excel class as for that we do need win32
