### ISSUE TITLE
create a set_cwd to allow users to quickly have access to their working environment

### ISSUE THREAD

**Issue by kfk** [kfk/grizly#74]
```
from grizly import set_cwd
set_cwd("acoe_projects")
```

Results in:

> 'C:\\Users\\eg013949\\acoe_projects'

So you can do:

`working_directory = set_cwd("acoe_projects", "new_project")`

and get:

> 'C:\\Users\\eg013949\\acoe_projects\\new_projects'

**Comment by kfk** [comment]
Done

**Comment by kfk** [comment]
https://github.com/kfk/grizly/commit/a23c7593e562cb57aeeb7fd63b6873388c2d76e6

**Comment by kfk** [comment]
@malinaa96, @pattrycja96 please review this issue, I have added new functionality to 0.2

**Comment by malinaa96** [comment]
As we discussed before I think we should change the name of the function, but I don't remember on which name we agreed.

**Comment by kfk** [comment]
I think it was get_path, another one could be to_path

Similar to to_rds, to_csv

Maybe to_path is the best one, what do you think?

**Comment by malinaa96** [comment]
I think get_path is better than to_path. We are using to_rds or to_csv to save the data somewhere - here we only want to get a path string.

**Comment by malinaa96** [comment]
As we are already using set_cwd I didn't delete it and I added get_path which works the same.  We can think of deleting set_cwd in next release
