### ISSUE TITLE
add read_finished_sql to blank notebook

### ISSUE THREAD

**Issue by vperluzzo** [kfk/grizly#78]
Can you add some examples where we provide an existing query (from an old project that we want to move to grizly) and then we use grizly functions to make the subqueries?

**Comment by kfk** [comment]
Me and @malinaa96 agreed that copying existing SQL into a QFrame is not a good idea, it will not work well. For instance you would not be able to use to_rds as to_rds needs the column names to automatically do a create table SQL statement.

We will need to migrate to the json. The good news is that once info is in the json it can take any form you want. Meaning we should not need to migrate manually any longer even if we change grizly or use another library
