### ISSUE TITLE
Add SFDC functions to Grizly

### ISSUE THREAD

**Issue by vperluzzo** [kfk/grizly#93]
SFDC Should be another option like Denodo/RDS, Michal has the functions but they haven't been implemented yet

**Comment by acivitillo** [comment]
@Trymzet before we go on with this let's understand how we approach the api

**Comment by michalz92** [comment]
Comments:
- select returns data of the form:

python```
result["records"] = 
{
    [
        (attributes, some_metadata),
        (field1, value1),
        (field2, value1),
    ],
    [
        (attributes, some_metadata),
        (field1, value2),
        (field2, value2),
    ],
}

```
- inserted data must be a list of dictionaries of the form:

python```
[
    {
        field1: value1, 
        field2: value1
    },
    {
        field1: value2, 
        field2: value2
    }
]
```

**Comment by vperluzzo** [comment]
@malinaa96 @michalz92 is this still pending/wont be done...?

**Comment by malinaa96** [comment]
As discussed with @acivitillo we will add it to `tools.py` as a separate class.

Related issue:
https://github.com/kfk/grizly/issues/111

**Comment by vperluzzo** [comment]
Ok, checked the #111 and I see the classes AWS, Excel and Email. If C2S will be another class, can you add it to that issue? Then we can close this one

**Comment by malinaa96** [comment]
I didn't add it cause I don't know what functions Michal has and I don't know which methods he wants to have in this class in fact I even don't know what should be the name of this class. We can close this issue and continue discussion on the other one.
